version: '3.8'

services:
  test-detection:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: intranet-test-detection
    volumes:
      - ./ip.txt:/app/ip.txt:ro
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
