services:
  redis:
    image: "redis:7-alpine"
    container_name: "redis_links"
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data: