services:
  redis:
    image: "redis:7-alpine"
    container_name: "redis_links"
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  parser_app:
    build: .
    container_name: parser_app
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    shm_size: '2gb'
    restart: unless-stopped

volumes:
  redis_data: