services:
  redis:
    image: redis:7-alpine
    container_name: intranet-redis
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}" ]
    ports: [ "6379:6379" ]
    volumes: [ "redis-data:/data" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  greenplum:
    image: andruche/greenplum:7
    platform: linux/amd64
    container_name: greenplum_db
    environment:
      GP_DB: ${GP_DB}
      GP_USER: ${GP_USER}
      GP_PASSWORD: ${GP_PASSWORD}
    ports: [ "54325:5432" ]
    volumes:
      - greenplum_data:/srv
      - ./init-db.sh:/init-db.sh
    command: [ "/bin/bash", "/init-db.sh" ]
    restart: unless-stopped

  dzen-parser:
    build:
      context: ..
      dockerfile: intranet/dzen_url_parser/Dockerfile
    env_file: [ .env ]
    container_name: dzen-parser
    ports: ["8091:8091"]
    depends_on:
      redis:
        condition: service_healthy

  scheduler:
    build:
      context: ..
      dockerfile: intranet/scheduler/Dockerfile
    env_file: [ .env ]
    container_name: scheduler-parsers
    ports: ["8090:8090"]
    depends_on: [ dzen-parser ]

  parser_app:
    build:
      context: .
      dockerfile: Dockerfile.parser
    container_name: parser_app
    depends_on:
      redis:
        condition: service_healthy
      greenplum:
        condition: service_started
    env_file: [ .env ]
    shm_size: '2gb'
    restart: unless-stopped

volumes:
  redis-data:
  greenplum_data:
