run:
  concurrency: 6
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - bodyclose
    - ineffassign
    - tparallel
    - unconvert
    - wastedassign

version: "2"