version: "2"

run:
  concurrency: 6
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - revive
    - bodyclose
    - ineffassign
    - tparallel
    - unconvert
    - wastedassign
    - whitespace
    - gocritic
    - gocyclo
  settings:
    gocritic:
      enable-all: true
      disabled-checks:
        - paramTypeCombine
        - hugeParam
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: package-comments
          disabled: true
