run:
  concurrency: 6
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - goimports
    - revive
    - bodyclose
    - ineffassign
    - tparallel
    - unconvert
    - wastedassign
    - whitespace
    - gocritic
    - gocyclo

linters-settings:
  gocritic:
    enable-all: true
  gocyclo:
    min-complexity: 15