services:
  bots_db:
    image: postgres:16-alpine
    container_name: bots_db
    environment:
      POSTGRES_USER: ${LOCAL_BOTS_DATABASE_USER}
      POSTGRES_PASSWORD: ${LOCAL_BOTS_DATABASE_PASSWORD}
      POSTGRES_DB: ${LOCAL_BOTS_DATABASE_NAME}
    ports:
      - "5433:5432"
    volumes:
      - bots_pgdata:/var/lib/postgresql/data
    networks:
      - kotyari-network
    restart: unless-stopped

  bots_go:
    build:
      context: .
      dockerfile: ./cmd/bots/Dockerfile
    container_name: bots_go
    image: bots_go_image
    env_file: .env
    ports:
      - "8001:8001"
    networks:
      - kotyari-network
    depends_on:
      - bots_db
    restart: unless-stopped

networks:
  kotyari-network:
    driver: bridge

volumes:
  bots_pgdata:
  profiles_pgdata: