version: '3.8'

services:
  profiles_db:
    image: postgres:16-alpine
    container_name: profiles_db
    environment:
      POSTGRES_USER: ${PROFILES_DB_USER}
      POSTGRES_PASSWORD: ${PROFILES_DB_PASSWORD}
      POSTGRES_DB: ${PROFILES_DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - profiles_pgdata:/var/lib/postgresql/data
    networks:
      - kotyari-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PROFILES_DB_USER} -d ${PROFILES_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  profiles_svc:
    build:
      context: .
      dockerfile: ./cmd/profiles/Dockerfile
    container_name: profiles_svc
    env_file: .env
    ports:
      - "8002:8002"
    networks:
      - kotyari-network
    depends_on:
      profiles_db:
        condition: service_healthy
    restart: unless-stopped

networks:
  kotyari-network:
    driver: bridge

volumes:
  profiles_pgdata: