CREATE TABLE IF NOT EXISTS integrations (
    "id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    "provider" text NOT NULL,
    "url" text NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
)