CREATE TABLE IF NOT EXISTS topics (
    "id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    "source" text NOT NULL,
    "text" text NOT NULL,
    "hash" text NOT NULL UNIQUE,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
)