PostID:
  name: postId
  in: path
  required: true
  description: "Уникальный идентификатор поста."
  schema:
    type: string
    format: uuid

GroupID:
  name: groupId
  in: path
  required: true
  description: "Уникальный идентификатор группы постов."
  schema:
    type: string
    format: uuid