bots_api:
  host: "0.0.0.0"
  port: 8001

bots_database:
  host: "bots_db"
  port: 5432
  user: "bots_user"
  password: "bots_password"
  name: "bots_db"
  sslmode: "disable"

profiles_api:
  port: 8002

profiles_database:
  host: "profiles_db"
  port: 5432
  user: "profiles_user"
  password: "profiles_password"
  name: "profiles_db"
  sslmode: "disable"

profiles_svc_addr: "profiles_svc:8002"