name: gci-format
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]

jobs:
  format-go:
    name: format-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24.5

      - name: Install tools
        run: make download-gci

      - name: Check Go Formatting
        run: make format-check