name: golangci-lint
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]

jobs:
  go-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ^1.24.5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
