name: push_pull
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    name: go-build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24.5

      - name: Get dependencies
        run: go mod tidy

      - name: Run make test
        run: go test ./...